version: '3'
services:
    web:
        image: nginx:1.15
        ports:
            - 8081:80
        depends_on:
            - app
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www/html
    app:
        build: ./docker/php-fpm
        volumes:
            - .:/var/www/html
        depends_on:
            - mysql
    mysql:
        image: mysql:8.0
        environment:
            MYSQL_DATABASE: programing
            MYSQL_USER: admin
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password
        ports:
            - "13306:3306"
        volumes:
            - ./mysql-data:/var/lib/mysql
